# Site settings
author: Yuliya Marinova
title: Yuliya's Blog
header-img: img/home-bg.png
email: yuliyambg@gmail.com
copyright_name: Yuliya Marinova
description: > # this means to ignore newlines until "baseurl:"
  Posts about Tech
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  yuliyambg

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
